//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClass.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_OrderDetail
    {
        public int OrderDetailID { get; set; }
        public int Price { get; set; }
        public int ClassID { get; set; }
        public int OrderID { get; set; }
    
        public virtual B_Order B_Order { get; set; }
        public virtual C_Class C_Class { get; set; }
    }
}
