//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClass.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Class
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_Class()
        {
            this.B_OrderDetail = new HashSet<B_OrderDetail>();
            this.B_ShoppingCar = new HashSet<B_ShoppingCar>();
            this.C_Lesson = new HashSet<C_Lesson>();
            this.M_MessageBoard = new HashSet<M_MessageBoard>();
            this.U_SmallBell = new HashSet<U_SmallBell>();
            this.UC_Follow = new HashSet<UC_Follow>();
            this.UC_Score = new HashSet<UC_Score>();
        }
    
        public int ClassID { get; set; }
        public string ClassName { get; set; }
        public int Price { get; set; }
        public byte[] MainPicture { get; set; }
        public string ClassContent { get; set; }
        public Nullable<System.DateTime> UpLoadTime { get; set; }
        public System.DateTime PreRegisterTime { get; set; }
        public System.DateTime RegisterTime { get; set; }
        public int NeedUser { get; set; }
        public int CreateUserID { get; set; }
        public int CreateTypeID { get; set; }
        public int ClassTypeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<B_OrderDetail> B_OrderDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<B_ShoppingCar> B_ShoppingCar { get; set; }
        public virtual C_ClassType C_ClassType { get; set; }
        public virtual C_CreateType C_CreateType { get; set; }
        public virtual U_User U_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Lesson> C_Lesson { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_MessageBoard> M_MessageBoard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<U_SmallBell> U_SmallBell { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UC_Follow> UC_Follow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UC_Score> UC_Score { get; set; }
    }
}
