//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClass.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_MessageBoard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public M_MessageBoard()
        {
            this.M_ReMessageBoard = new HashSet<M_ReMessageBoard>();
            this.M_Report = new HashSet<M_Report>();
        }
    
        public int MessageBoardID { get; set; }
        public string MessageBoardContent { get; set; }
        public System.DateTime PostTime { get; set; }
        public bool Status { get; set; }
        public int UserID { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<int> LessonID { get; set; }
        public int PostTypeID { get; set; }
    
        public virtual C_Class C_Class { get; set; }
        public virtual C_Lesson C_Lesson { get; set; }
        public virtual M_PostType M_PostType { get; set; }
        public virtual U_User U_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_ReMessageBoard> M_ReMessageBoard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_Report> M_Report { get; set; }
    }
}
