//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClass.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UC_Score
    {
        public int ScoreID { get; set; }
        public int Score { get; set; }
        public string ScoreContent { get; set; }
        public int UserID { get; set; }
        public int ClassID { get; set; }
    
        public virtual C_Class C_Class { get; set; }
        public virtual U_User U_User { get; set; }
    }
}
