//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClass.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AOnlineClassEntities : DbContext
    {
        public AOnlineClassEntities()
            : base("name=AOnlineClassEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<B_Order> B_Order { get; set; }
        public virtual DbSet<B_OrderDetail> B_OrderDetail { get; set; }
        public virtual DbSet<B_ShoppingCar> B_ShoppingCar { get; set; }
        public virtual DbSet<C_Class> C_Class { get; set; }
        public virtual DbSet<C_ClassType> C_ClassType { get; set; }
        public virtual DbSet<C_CreateType> C_CreateType { get; set; }
        public virtual DbSet<C_Lesson> C_Lesson { get; set; }
        public virtual DbSet<C_LessonCheckTime> C_LessonCheckTime { get; set; }
        public virtual DbSet<M_MessageBoard> M_MessageBoard { get; set; }
        public virtual DbSet<M_PostType> M_PostType { get; set; }
        public virtual DbSet<M_ReMessageBoard> M_ReMessageBoard { get; set; }
        public virtual DbSet<M_Report> M_Report { get; set; }
        public virtual DbSet<M_SolutionType> M_SolutionType { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<U_Permission> U_Permission { get; set; }
        public virtual DbSet<U_Skill> U_Skill { get; set; }
        public virtual DbSet<U_SkillType> U_SkillType { get; set; }
        public virtual DbSet<U_SkillTypeCategory> U_SkillTypeCategory { get; set; }
        public virtual DbSet<U_SmallBell> U_SmallBell { get; set; }
        public virtual DbSet<U_StatusType> U_StatusType { get; set; }
        public virtual DbSet<U_User> U_User { get; set; }
        public virtual DbSet<U_UserSkill> U_UserSkill { get; set; }
        public virtual DbSet<UC_Follow> UC_Follow { get; set; }
        public virtual DbSet<UC_Score> UC_Score { get; set; }
    }
}
